# Site settings

# NB! Set your site's url, otherwise nothing will work
url: "https://ajosephau.github.io"

# Google tracking id
google-tracking-id: False

#############
# HTML Head #
#############
lang: "en"
author: "Anthony I. Joseph"
title: "Anthony I. Joseph's blog"
description: "The blog and website of Anthony I. Joseph, blogging mainly for tech. Opinions expressed are mine."
keywords: "anthony, joseph, personal, developer, engineer"
favicon: "/img/favicon.ico"
################
# Header layout #
################
black-favicon: "/img/favicon-black.ico"
background-img: False
##############################
# Dynamic Text on the Header #
##############################
dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "A ship is always safe at the shore, but that is not what it is built for. (Albert Einstein)"
  - text: "You are enough just as you are (Meghan Markle)"
  - text: "We can’t be brave without fear (Muhammad Ali)"
me-img: "/img/pfp.png"
# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#1e1e1e"
apple-status-bar-style: "black"
################
# Web app mode #
################
web-app-mode: True
# Icons for Web App mode
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"
########
# Blog #
########
post-preview-words: 96
paginate: 8
email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True
disqus-shortname: "ajosephau-github-io"
syntax-highlight: True
############
# Timeline #
############
events:
  - image: "/img/timeline/bike-party.jpeg"
    date: "Jan 2016 – Present"
    description: "My House Geek/Bike Party (Technical cofounder)"
  - image: "/img/timeline/onlifeinc.jpeg"
    date: "Sept 2024 – Present"
    description: "Onlife (Senior software engineer)"
  - image: "/img/timeline/the_yield.jpeg"
    date: "Oct 2022 – Jun 2024"
    description: "The Yield (Senior software engineer)"
  - image: "/img/timeline/fetchtv.jpeg"
    date: "Jan 2020 – Oct 2022"
    description: "FetchTV (Middleware software engineer)"
  - image: "/img/timeline/assignar.jpeg"
    date: "Mar 2017 – Jan 2020"
    description: "Assignar (Backend software engineer)"
  - image: "/img/timeline/prezzee.jpeg"
    date: "Mar 2017 – Jan 2020"
    description: "Prezzee (Full stack software engineer)"
  - image: "/img/timeline/coder-factory.jpeg"
    date: "Feb 2017 – Jun 2017"
    description: "Coder Factory Academy (Full stack software engineer)"
  - image: "/img/timeline/uts.jpeg"
    date: "Jan 2013 - Dec 2015"
    description: "Masters of Business & Technology: University of Technology, Sydney Grade Point Average: 3.62/4. Weighted Average Mean (Estimated): 83/100"
  - image: "/img/timeline/dst.jpeg"
    date: "Aug 2010 – Jan 2016"
    description: "Defence Science and Technology Group, Department of Defence (Software engineer and data scientist)"
  - image: "/img/timeline/defence.jpeg"
    date: "Jan 2010 – Jul 2010"
    description: "Defence Materiel Organisation, Department of Defence (Software engineer)"
  - image: "/img/timeline/wolfram.jpeg"
    date: "Jan 2009 – Feb 2009"
    description: "Wolfram Research Inc., Special Projects Division (Undergraduate Software Engineer)"
  - image: "/img/timeline/raytheon.jpeg"
    date: "Aug 2007 – Aug 2008"
    description: "Raytheon Australia, Air Warfare Destroyer Project (Undergraduate Systems Engineer)"
  - image: "/img/timeline/thales.jpeg"
    date: "Aug 2005 – Feb 2007"
    description: "Thales Australia, FFG Upgrade (Undergraduate Systems Engineer and Data Scientist)"
  - image: "/img/timeline/uts.jpeg"
    date: "Jan 2004 - Dec 2009"
    description: "Bachelors of Engineering (Software Engineering) Diploma of Engineering Practice with First Class Honours Bachelors of Science (Mathematics): University of Technology, Sydney Grade Point Average: 3.90/4. Weighted Average Mean (Estimated): 90.43/100"
# First image of the Timeline
timeline-img: "/img/timeline/default.png"
###########
# Contact #
###########
email: "ajosephau@fastmail.com.au"
# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False
################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb:
  "Anthony is an Australian software engineer and mathematician. As a UTS MBT graduate, Anthony is the technology 
  co-founder of a property and cycling-tech startup and enjoys teaching and learning coding with the Australian 
  startup scene."
author_blurb_image: "/img/author.png"
##################
# Social Buttons #
##################
social:
  - icon: "github"
    url: "https://github.com/ajosephau"
  - icon: "linkedin-in"
    url: "https://www.linkedin.com/in/anthony-joseph"
  - icon: "x-twitter"
    url: "https://twitter.com/ajosephau"
  - icon: "mastodon"
    url: "https://indieweb.social/@ajosephau"
############
# 404 page #
############
err-404-img: "/img/404.png"
################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Blog: "latest-post"
  Resume: "timeline"
  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
